# Exercise Numpy Arrays

In [2]:
import numpy as np
import random

## Question 1

Create a function generate_temperature that accepts a min and max range, and then number of temperatures count that need to be created. This function must return a list with count temperatures.

In [3]:
def generate_temperature(min_temp, max_temp, count):
    return [random.uniform(min_temp, max_temp) for _ in range(count)]

## Question 2

Create a numpy array temperature_data that has 7-day temperature readings for 5 cities. Limit the temperature to be between 15 and 35.

In [4]:
temperature_data = np.random.uniform(15, 35, size=(5, 7)).round(2)

## Question 3

Print the shape of temperature_data to ensure its (5,7).

In [5]:
print("3. Shape of temperature_data:", temperature_data.shape)

3. Shape of temperature_data: (5, 7)


## Question 4

Display the overall average_temperature.

In [6]:
average_temperature = temperature_data.mean()
print("4. Overall average temperature:", round(average_temperature, 2), "°C")

4. Overall average temperature: 25.89 °C


## Question 5

Display the average temperature per city.

In [7]:
avg_per_city = temperature_data.mean(axis=1)
print("5. Average temperature per city (°C):", avg_per_city.round(2))

5. Average temperature per city (°C): [24.96 25.5  27.54 27.16 24.28]


## Question 6

Extract the temperature data for the first 3 days of City B, and print them.

In [8]:
city_b_first3 = temperature_data[1, 0:3]
print("6. City B, first 3 days:", city_b_first3)

6. City B, first 3 days: [23.12 27.58 33.77]


## Question 7

Create a new numpy array temperature_f that has all the values covnerted to fahrenheit. Display the overall average temperature in F.

In [9]:
temperature_f = (temperature_data * 9/5) + 32
print("7. Overall average temperature in Fahrenheit:", round(temperature_f.mean(), 2), "°F")

7. Overall average temperature in Fahrenheit: 78.6 °F


## Question 8

Find the day with the highest temperature for City D. Display the day number, and the relative temperature.

In [10]:
city_d = temperature_data[3]
day_index = np.argmax(city_d)
max_temp = city_d[day_index]
print(f"8. City D's highest temperature is on Day {day_index + 1}: {max_temp} °C")

8. City D's highest temperature is on Day 1: 34.72 °C


## Question 9

Create a new numpy array all_temps with a 1D array of all temperatures.

In [11]:
all_temps = temperature_data.flatten()
print("9. 1D array of all temperatures:", all_temps)

9. 1D array of all temperatures: [20.33 32.06 22.37 32.09 21.8  16.6  29.49 23.12 27.58 33.77 28.92 17.09
 32.03 16.02 26.99 26.02 32.22 21.66 28.53 33.75 23.58 34.72 22.28 29.06
 29.16 22.37 32.79 19.75 18.75 28.56 26.72 25.64 22.3  19.57 28.43]


## Question 10

For each city, calculate the temperature difference between the highest and the lowest temperatures. Then, display the highest fluctuation.

In [12]:
fluctuations = temperature_data.max(axis=1) - temperature_data.min(axis=1)
print("10. Temperature fluctuations per city:", fluctuations.round(2))
print("    Highest fluctuation:", round(fluctuations.max(), 2), "°C")

10. Temperature fluctuations per city: [15.49 17.75 12.09 14.97  9.81]
    Highest fluctuation: 17.75 °C


## Question 11

Generate a numpy array weights that has 7 values evenly spread out from 0 to 1. Then multiply these weights with the temperatures.

In [13]:
weights = np.linspace(0, 1, 7)
weighted_temps = temperature_data * weights
print("11. Weighted temperatures (with weights 0 to 1):")
print(weighted_temps.round(2))

11. Weighted temperatures (with weights 0 to 1):
[[ 0.    5.34  7.46 16.05 14.53 13.83 29.49]
 [ 0.    4.6  11.26 14.46 11.39 26.69 16.02]
 [ 0.    4.34 10.74 10.83 19.02 28.12 23.58]
 [ 0.    3.71  9.69 14.58 14.91 27.32 19.75]
 [ 0.    4.76  8.91 12.82 14.87 16.31 28.43]]


## Question 12

Given a heat index of [1.1, 1.2, 1.1, 1.3, 1.2, 1.1, 1.2], display the total heat index for each city.

In [14]:
heat_index = np.array([1.1, 1.2, 1.1, 1.3, 1.2, 1.1, 1.2])
total_heat_index = (temperature_data * heat_index).sum(axis=1)
print("12. Total heat index per city:", total_heat_index.round(2))

12. Total heat index per city: [206.97 208.24 224.17 221.42 200.02]
